blank_issues_enabled: true
contact_links:
  - name: 📚 SIX Webcomponents Documentation
    url: https://six-group.github.io/six-webcomponents/
    about: Check the documentation for usage of SIX Webcomponents
