// eslint-disable-next-line @stencil-community/ban-exported-const-enums
export enum SixFileUploadFailureErrorCode {
  ONLY_ONE_FILE_ALLOWED = 'ONLY_ONE_FILE_ALLOWED',
  ONE_OR_MORE_FILES_HAVE_INVALID_MIME_TYPE = 'ONE_OR_MORE_FILES_HAVE_INVALID_MIME_TYPE',
  INVALID_MIME_TYPE = 'INVALID_MIME_TYPE',
  ONE_OR_MULTIPLE_FILES_TOO_BIG = 'ONE_OR_MULTIPLE_FILES_TOO_BIG',
  FILE_TOO_BIG = 'FILE_TOO_BIG',
}
