import type { Metadata } from 'next';
import './globals.css';
import { SixRoot } from '@six-group/ui-library-react';
import Header from '@/app/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SixRoot>
          <Header open={false} taskCount={1} />
          <main>{children}</main>
        </SixRoot>
      </body>
    </html>
  );
}
