/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type EmptyPayload, type SixAlertCustomEvent, type SixButtonCustomEvent, type SixCheckboxCustomEvent, type SixDatepickerCustomEvent, type SixDatepickerSelectPayload, type SixDetailsCustomEvent, type SixDialogCustomEvent, type SixDialogRequestClose, type SixDrawerCustomEvent, type SixDrawerRequestClose, type SixDropdownAsyncFilterPayload, type SixDropdownAutoFilterPayload, type SixDropdownCustomEvent, type SixDropdownScrollPayload, type SixFileListDownloadPayload, type SixFileListItemCustomEvent, type SixFileListRemovePayload, type SixFileUploadCustomEvent, type SixFileUploadFailurePayload, type SixFileUploadSuccessPayload, type SixInputCustomEvent, type SixItemPickerChangePayload, type SixItemPickerCustomEvent, type SixLanguageSwitcherChangePayload, type SixLanguageSwitcherCustomEvent, type SixMenuCustomEvent, type SixMenuItemSelectedPayload, type SixRadioCustomEvent, type SixRangeCustomEvent, type SixSearchFieldChangePayload, type SixSearchFieldCustomEvent, type SixSelectChangePayload, type SixSelectCustomEvent, type SixSidebarCustomEvent, type SixSwitchCustomEvent, type SixTabCustomEvent, type SixTabGroupCustomEvent, type SixTabHidePayload, type SixTabShowPayload, type SixTagCustomEvent, type SixTextareaCustomEvent, type SixTileCustomEvent, type SixTimepickerChange, type SixTimepickerCustomEvent, type SixTooltipCustomEvent } from "@six-group/ui-library";
import { SixAlert as SixAlertElement } from "@six-group/ui-library/dist/components/six-alert.js";
import { SixAvatar as SixAvatarElement } from "@six-group/ui-library/dist/components/six-avatar.js";
import { SixBadge as SixBadgeElement } from "@six-group/ui-library/dist/components/six-badge.js";
import { SixButton as SixButtonElement } from "@six-group/ui-library/dist/components/six-button.js";
import { SixCard as SixCardElement } from "@six-group/ui-library/dist/components/six-card.js";
import { SixCheckbox as SixCheckboxElement } from "@six-group/ui-library/dist/components/six-checkbox.js";
import { SixDate as SixDateElement } from "@six-group/ui-library/dist/components/six-date.js";
import { SixDatepicker as SixDatepickerElement } from "@six-group/ui-library/dist/components/six-datepicker.js";
import { SixDetails as SixDetailsElement } from "@six-group/ui-library/dist/components/six-details.js";
import { SixDialog as SixDialogElement } from "@six-group/ui-library/dist/components/six-dialog.js";
import { SixDrawer as SixDrawerElement } from "@six-group/ui-library/dist/components/six-drawer.js";
import { SixDropdown as SixDropdownElement } from "@six-group/ui-library/dist/components/six-dropdown.js";
import { SixErrorPage as SixErrorPageElement } from "@six-group/ui-library/dist/components/six-error-page.js";
import { SixError as SixErrorElement } from "@six-group/ui-library/dist/components/six-error.js";
import { SixFileListItem as SixFileListItemElement } from "@six-group/ui-library/dist/components/six-file-list-item.js";
import { SixFileList as SixFileListElement } from "@six-group/ui-library/dist/components/six-file-list.js";
import { SixFileUpload as SixFileUploadElement } from "@six-group/ui-library/dist/components/six-file-upload.js";
import { SixFooter as SixFooterElement } from "@six-group/ui-library/dist/components/six-footer.js";
import { SixGroupLabel as SixGroupLabelElement } from "@six-group/ui-library/dist/components/six-group-label.js";
import { SixHeaderDropdownItem as SixHeaderDropdownItemElement } from "@six-group/ui-library/dist/components/six-header-dropdown-item.js";
import { SixHeaderItem as SixHeaderItemElement } from "@six-group/ui-library/dist/components/six-header-item.js";
import { SixHeaderMenuButton as SixHeaderMenuButtonElement } from "@six-group/ui-library/dist/components/six-header-menu-button.js";
import { SixHeader as SixHeaderElement } from "@six-group/ui-library/dist/components/six-header.js";
import { SixIconButton as SixIconButtonElement } from "@six-group/ui-library/dist/components/six-icon-button.js";
import { SixIcon as SixIconElement } from "@six-group/ui-library/dist/components/six-icon.js";
import { SixInput as SixInputElement } from "@six-group/ui-library/dist/components/six-input.js";
import { SixItemPicker as SixItemPickerElement } from "@six-group/ui-library/dist/components/six-item-picker.js";
import { SixLanguageSwitcher as SixLanguageSwitcherElement } from "@six-group/ui-library/dist/components/six-language-switcher.js";
import { SixLayoutGrid as SixLayoutGridElement } from "@six-group/ui-library/dist/components/six-layout-grid.js";
import { SixLogo as SixLogoElement } from "@six-group/ui-library/dist/components/six-logo.js";
import { SixMainContainer as SixMainContainerElement } from "@six-group/ui-library/dist/components/six-main-container.js";
import { SixMenuDivider as SixMenuDividerElement } from "@six-group/ui-library/dist/components/six-menu-divider.js";
import { SixMenuItem as SixMenuItemElement } from "@six-group/ui-library/dist/components/six-menu-item.js";
import { SixMenuLabel as SixMenuLabelElement } from "@six-group/ui-library/dist/components/six-menu-label.js";
import { SixMenu as SixMenuElement } from "@six-group/ui-library/dist/components/six-menu.js";
import { SixPicto as SixPictoElement } from "@six-group/ui-library/dist/components/six-picto.js";
import { SixProgressBar as SixProgressBarElement } from "@six-group/ui-library/dist/components/six-progress-bar.js";
import { SixProgressRing as SixProgressRingElement } from "@six-group/ui-library/dist/components/six-progress-ring.js";
import { SixRadio as SixRadioElement } from "@six-group/ui-library/dist/components/six-radio.js";
import { SixRange as SixRangeElement } from "@six-group/ui-library/dist/components/six-range.js";
import { SixRoot as SixRootElement } from "@six-group/ui-library/dist/components/six-root.js";
import { SixSearchField as SixSearchFieldElement } from "@six-group/ui-library/dist/components/six-search-field.js";
import { SixSelect as SixSelectElement } from "@six-group/ui-library/dist/components/six-select.js";
import { SixSidebarItemGroup as SixSidebarItemGroupElement } from "@six-group/ui-library/dist/components/six-sidebar-item-group.js";
import { SixSidebarItem as SixSidebarItemElement } from "@six-group/ui-library/dist/components/six-sidebar-item.js";
import { SixSidebar as SixSidebarElement } from "@six-group/ui-library/dist/components/six-sidebar.js";
import { SixSpinner as SixSpinnerElement } from "@six-group/ui-library/dist/components/six-spinner.js";
import { SixStageIndicator as SixStageIndicatorElement } from "@six-group/ui-library/dist/components/six-stage-indicator.js";
import { SixSwitch as SixSwitchElement } from "@six-group/ui-library/dist/components/six-switch.js";
import { SixTabGroup as SixTabGroupElement } from "@six-group/ui-library/dist/components/six-tab-group.js";
import { SixTabPanel as SixTabPanelElement } from "@six-group/ui-library/dist/components/six-tab-panel.js";
import { SixTab as SixTabElement } from "@six-group/ui-library/dist/components/six-tab.js";
import { SixTag as SixTagElement } from "@six-group/ui-library/dist/components/six-tag.js";
import { SixTextarea as SixTextareaElement } from "@six-group/ui-library/dist/components/six-textarea.js";
import { SixTile as SixTileElement } from "@six-group/ui-library/dist/components/six-tile.js";
import { SixTimepicker as SixTimepickerElement } from "@six-group/ui-library/dist/components/six-timepicker.js";
import { SixTooltip as SixTooltipElement } from "@six-group/ui-library/dist/components/six-tooltip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SixAlertEvents = {
    onSixAlertShow: EventName<SixAlertCustomEvent<EmptyPayload>>,
    onSixAlertAfterShow: EventName<SixAlertCustomEvent<EmptyPayload>>,
    onSixAlertHide: EventName<SixAlertCustomEvent<EmptyPayload>>,
    onSixAlertAfterHide: EventName<SixAlertCustomEvent<EmptyPayload>>
};

export const SixAlert: StencilReactComponent<SixAlertElement, SixAlertEvents> = /*@__PURE__*/ createComponent<SixAlertElement, SixAlertEvents>({
    tagName: 'six-alert',
    properties: {
        open: 'open',
        closable: 'closable',
        type: 'type',
        duration: 'duration'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixAvatarEvents = NonNullable<unknown>;

export const SixAvatar: StencilReactComponent<SixAvatarElement, SixAvatarEvents> = /*@__PURE__*/ createComponent<SixAvatarElement, SixAvatarEvents>({
    tagName: 'six-avatar',
    properties: {
        image: 'image',
        alt: 'alt',
        initials: 'initials',
        shape: 'shape'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixBadgeEvents = NonNullable<unknown>;

export const SixBadge: StencilReactComponent<SixBadgeElement, SixBadgeEvents> = /*@__PURE__*/ createComponent<SixBadgeElement, SixBadgeEvents>({
    tagName: 'six-badge',
    properties: {
        type: 'type',
        pill: 'pill',
        pulse: 'pulse'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixButtonEvents = {
    onSixButtonBlur: EventName<SixButtonCustomEvent<EmptyPayload>>,
    onSixButtonFocus: EventName<SixButtonCustomEvent<EmptyPayload>>
};

export const SixButton: StencilReactComponent<SixButtonElement, SixButtonEvents> = /*@__PURE__*/ createComponent<SixButtonElement, SixButtonEvents>({
    tagName: 'six-button',
    properties: {
        type: 'type',
        size: 'size',
        caret: 'caret',
        disabled: 'disabled',
        loading: 'loading',
        pill: 'pill',
        circle: 'circle',
        submit: 'submit',
        reset: 'reset',
        name: 'name',
        value: 'value',
        href: 'href',
        target: 'target',
        download: 'download'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixCardEvents = NonNullable<unknown>;

export const SixCard: StencilReactComponent<SixCardElement, SixCardEvents> = /*@__PURE__*/ createComponent<SixCardElement, SixCardEvents>({
    tagName: 'six-card',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixCheckboxEvents = {
    onSixCheckboxBlur: EventName<SixCheckboxCustomEvent<EmptyPayload>>,
    onSixCheckboxChange: EventName<SixCheckboxCustomEvent<EmptyPayload>>,
    onSixCheckboxFocus: EventName<SixCheckboxCustomEvent<EmptyPayload>>
};

export const SixCheckbox: StencilReactComponent<SixCheckboxElement, SixCheckboxEvents> = /*@__PURE__*/ createComponent<SixCheckboxElement, SixCheckboxEvents>({
    tagName: 'six-checkbox',
    properties: {
        name: 'name',
        value: 'value',
        disabled: 'disabled',
        required: 'required',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        checked: 'checked',
        indeterminate: 'indeterminate'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDateEvents = {
    onSixChange: EventName<CustomEvent<string | ''>>,
    onSixBlur: EventName<CustomEvent<any>>
};

export const SixDate: StencilReactComponent<SixDateElement, SixDateEvents> = /*@__PURE__*/ createComponent<SixDateElement, SixDateEvents>({
    tagName: 'six-date',
    properties: {
        language: 'language',
        readonly: 'readonly',
        disabled: 'disabled',
        allowedDates: 'allowed-dates',
        min: 'min',
        max: 'max',
        size: 'size',
        required: 'required',
        placeholder: 'placeholder',
        value: 'value',
        dateFormat: 'date-format',
        label: 'label',
        helpText: 'help-text',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        name: 'name',
        clearable: 'clearable'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDatepickerEvents = {
    onSixDatepickerSelect: EventName<SixDatepickerCustomEvent<SixDatepickerSelectPayload>>,
    onSixDatepickerClear: EventName<SixDatepickerCustomEvent<EmptyPayload>>,
    onSixDatepickerBlur: EventName<SixDatepickerCustomEvent<SixDatepickerSelectPayload>>
};

export const SixDatepicker: StencilReactComponent<SixDatepickerElement, SixDatepickerEvents> = /*@__PURE__*/ createComponent<SixDatepickerElement, SixDatepickerEvents>({
    tagName: 'six-datepicker',
    properties: {
        type: 'type',
        locale: 'locale',
        open: 'open',
        inline: 'inline',
        readonly: 'readonly',
        disabled: 'disabled',
        allowedDates: 'allowed-dates',
        min: 'min',
        max: 'max',
        closeOnSelect: 'close-on-select',
        placement: 'placement',
        size: 'size',
        required: 'required',
        defaultDate: 'default-date',
        placeholder: 'placeholder',
        value: 'value',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        containingElement: 'containing-element',
        dateFormat: 'date-format',
        debounce: 'debounce',
        name: 'name',
        clearable: 'clearable',
        iconPosition: 'icon-position',
        hoist: 'hoist'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDetailsEvents = {
    onSixDetailsShow: EventName<SixDetailsCustomEvent<EmptyPayload>>,
    onSixDetailsAfterShow: EventName<SixDetailsCustomEvent<EmptyPayload>>,
    onSixDetailsHide: EventName<SixDetailsCustomEvent<EmptyPayload>>,
    onSixDetailsAfterHide: EventName<SixDetailsCustomEvent<EmptyPayload>>
};

export const SixDetails: StencilReactComponent<SixDetailsElement, SixDetailsEvents> = /*@__PURE__*/ createComponent<SixDetailsElement, SixDetailsEvents>({
    tagName: 'six-details',
    properties: {
        open: 'open',
        summary: 'summary',
        summaryIcon: 'summary-icon',
        summaryIconSize: 'summary-icon-size',
        disabled: 'disabled',
        inline: 'inline',
        selectableEmpty: 'selectable-empty',
        hasContent: 'has-content'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDialogEvents = {
    onSixDialogShow: EventName<SixDialogCustomEvent<EmptyPayload>>,
    onSixDialogAfterShow: EventName<SixDialogCustomEvent<EmptyPayload>>,
    onSixDialogHide: EventName<SixDialogCustomEvent<EmptyPayload>>,
    onSixDialogAfterHide: EventName<SixDialogCustomEvent<EmptyPayload>>,
    onSixDialogInitialFocus: EventName<SixDialogCustomEvent<EmptyPayload>>,
    onSixDialogRequestClose: EventName<SixDialogCustomEvent<SixDialogRequestClose>>
};

export const SixDialog: StencilReactComponent<SixDialogElement, SixDialogEvents> = /*@__PURE__*/ createComponent<SixDialogElement, SixDialogEvents>({
    tagName: 'six-dialog',
    properties: {
        open: 'open',
        label: 'label',
        noHeader: 'no-header'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDrawerEvents = {
    onSixDrawerShow: EventName<SixDrawerCustomEvent<EmptyPayload>>,
    onSixDrawerAfterShow: EventName<SixDrawerCustomEvent<EmptyPayload>>,
    onSixDrawerHide: EventName<SixDrawerCustomEvent<EmptyPayload>>,
    onSixDrawerAfterHide: EventName<SixDrawerCustomEvent<EmptyPayload>>,
    onSixDrawerInitialFocus: EventName<SixDrawerCustomEvent<EmptyPayload>>,
    onSixDrawerRequestClose: EventName<SixDrawerCustomEvent<SixDrawerRequestClose>>
};

export const SixDrawer: StencilReactComponent<SixDrawerElement, SixDrawerEvents> = /*@__PURE__*/ createComponent<SixDrawerElement, SixDrawerEvents>({
    tagName: 'six-drawer',
    properties: {
        open: 'open',
        label: 'label',
        placement: 'placement',
        contained: 'contained',
        noHeader: 'no-header'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixDropdownEvents = {
    onSixDropdownShow: EventName<SixDropdownCustomEvent<EmptyPayload>>,
    onSixDropdownAfterShow: EventName<SixDropdownCustomEvent<EmptyPayload>>,
    onSixDropdownHide: EventName<SixDropdownCustomEvent<EmptyPayload>>,
    onSixDropdownAfterHide: EventName<SixDropdownCustomEvent<EmptyPayload>>,
    onSixDropdownAutoFilterFired: EventName<SixDropdownCustomEvent<SixDropdownAutoFilterPayload>>,
    onSixAsyncFilterFired: EventName<SixDropdownCustomEvent<SixDropdownAsyncFilterPayload>>,
    onSixDropdownScroll: EventName<SixDropdownCustomEvent<SixDropdownScrollPayload>>
};

export const SixDropdown: StencilReactComponent<SixDropdownElement, SixDropdownEvents> = /*@__PURE__*/ createComponent<SixDropdownElement, SixDropdownEvents>({
    tagName: 'six-dropdown',
    properties: {
        open: 'open',
        placement: 'placement',
        closeOnSelect: 'close-on-select',
        distance: 'distance',
        skidding: 'skidding',
        hoist: 'hoist',
        containingElement: 'containing-element',
        filter: 'filter',
        asyncFilter: 'async-filter',
        filterPlaceholder: 'filter-placeholder',
        autofocusFilter: 'autofocus-filter',
        filterDebounce: 'filter-debounce',
        disableHideOnEnterAndSpace: 'disable-hide-on-enter-and-space',
        options: 'options',
        virtualScroll: 'virtual-scroll',
        matchTriggerWidth: 'match-trigger-width'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixErrorEvents = NonNullable<unknown>;

export const SixError: StencilReactComponent<SixErrorElement, SixErrorEvents> = /*@__PURE__*/ createComponent<SixErrorElement, SixErrorEvents>({
    tagName: 'six-error',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixErrorPageEvents = NonNullable<unknown>;

export const SixErrorPage: StencilReactComponent<SixErrorPageElement, SixErrorPageEvents> = /*@__PURE__*/ createComponent<SixErrorPageElement, SixErrorPageEvents>({
    tagName: 'six-error-page',
    properties: {
        errorCode: 'error-code',
        language: 'language',
        customTitle: 'custom-title',
        customDescription: 'custom-description',
        customIcon: 'custom-icon'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixFileListEvents = NonNullable<unknown>;

export const SixFileList: StencilReactComponent<SixFileListElement, SixFileListEvents> = /*@__PURE__*/ createComponent<SixFileListElement, SixFileListEvents>({
    tagName: 'six-file-list',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixFileListItemEvents = {
    onSixFileListItemDownload: EventName<SixFileListItemCustomEvent<SixFileListDownloadPayload>>,
    onSixFileListItemRemove: EventName<SixFileListItemCustomEvent<SixFileListRemovePayload>>
};

export const SixFileListItem: StencilReactComponent<SixFileListItemElement, SixFileListItemEvents> = /*@__PURE__*/ createComponent<SixFileListItemElement, SixFileListItemEvents>({
    tagName: 'six-file-list-item',
    properties: {
        identifier: 'identifier',
        name: 'name',
        date: 'date',
        size: 'size',
        nodownload: 'nodownload',
        nodelete: 'nodelete'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixFileUploadEvents = {
    onSixFileUploadSuccess: EventName<SixFileUploadCustomEvent<SixFileUploadSuccessPayload>>,
    onSixFileUploadFailure: EventName<SixFileUploadCustomEvent<SixFileUploadFailurePayload>>
};

export const SixFileUpload: StencilReactComponent<SixFileUploadElement, SixFileUploadEvents> = /*@__PURE__*/ createComponent<SixFileUploadElement, SixFileUploadEvents>({
    tagName: 'six-file-upload',
    properties: {
        compact: 'compact',
        label: 'label',
        disabled: 'disabled',
        accept: 'accept',
        multiple: 'multiple',
        maxFileSize: 'max-file-size',
        uploading: 'uploading',
        errorText: 'error-text',
        invalid: 'invalid'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixFooterEvents = NonNullable<unknown>;

export const SixFooter: StencilReactComponent<SixFooterElement, SixFooterEvents> = /*@__PURE__*/ createComponent<SixFooterElement, SixFooterEvents>({
    tagName: 'six-footer',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixGroupLabelEvents = NonNullable<unknown>;

export const SixGroupLabel: StencilReactComponent<SixGroupLabelElement, SixGroupLabelEvents> = /*@__PURE__*/ createComponent<SixGroupLabelElement, SixGroupLabelEvents>({
    tagName: 'six-group-label',
    properties: {
        size: 'size',
        label: 'label',
        helpText: 'help-text',
        disabled: 'disabled',
        required: 'required'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixHeaderEvents = NonNullable<unknown>;

export const SixHeader: StencilReactComponent<SixHeaderElement, SixHeaderEvents> = /*@__PURE__*/ createComponent<SixHeaderElement, SixHeaderEvents>({
    tagName: 'six-header',
    properties: {
        shiftContent: 'shift-content',
        openSearch: 'open-search'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixHeaderDropdownItemEvents = NonNullable<unknown>;

export const SixHeaderDropdownItem: StencilReactComponent<SixHeaderDropdownItemElement, SixHeaderDropdownItemEvents> = /*@__PURE__*/ createComponent<SixHeaderDropdownItemElement, SixHeaderDropdownItemEvents>({
    tagName: 'six-header-dropdown-item',
    properties: {
        filter: 'filter',
        filterPlaceholder: 'filter-placeholder'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixHeaderItemEvents = NonNullable<unknown>;

export const SixHeaderItem: StencilReactComponent<SixHeaderItemElement, SixHeaderItemEvents> = /*@__PURE__*/ createComponent<SixHeaderItemElement, SixHeaderItemEvents>({
    tagName: 'six-header-item',
    properties: { active: 'active' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixHeaderMenuButtonEvents = NonNullable<unknown>;

export const SixHeaderMenuButton: StencilReactComponent<SixHeaderMenuButtonElement, SixHeaderMenuButtonEvents> = /*@__PURE__*/ createComponent<SixHeaderMenuButtonElement, SixHeaderMenuButtonEvents>({
    tagName: 'six-header-menu-button',
    properties: {
        caret: 'caret',
        disabled: 'disabled',
        loading: 'loading',
        submit: 'submit',
        reset: 'reset'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixIconEvents = NonNullable<unknown>;

export const SixIcon: StencilReactComponent<SixIconElement, SixIconEvents> = /*@__PURE__*/ createComponent<SixIconElement, SixIconEvents>({
    tagName: 'six-icon',
    properties: {
        size: 'size',
        filled: 'filled'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixIconButtonEvents = NonNullable<unknown>;

export const SixIconButton: StencilReactComponent<SixIconButtonElement, SixIconButtonEvents> = /*@__PURE__*/ createComponent<SixIconButtonElement, SixIconButtonEvents>({
    tagName: 'six-icon-button',
    properties: {
        name: 'name',
        size: 'size',
        label: 'label',
        disabled: 'disabled',
        html: 'html',
        href: 'href',
        target: 'target',
        download: 'download'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixInputEvents = {
    onSixInputChange: EventName<SixInputCustomEvent<EmptyPayload>>,
    onSixInputClear: EventName<SixInputCustomEvent<EmptyPayload>>,
    onSixInputInput: EventName<SixInputCustomEvent<EmptyPayload>>,
    onSixInputFocus: EventName<SixInputCustomEvent<EmptyPayload>>,
    onSixInputBlur: EventName<SixInputCustomEvent<EmptyPayload>>
};

export const SixInput: StencilReactComponent<SixInputElement, SixInputEvents> = /*@__PURE__*/ createComponent<SixInputElement, SixInputEvents>({
    tagName: 'six-input',
    properties: {
        type: 'type',
        size: 'size',
        name: 'name',
        value: 'value',
        pill: 'pill',
        helpText: 'help-text',
        placeholder: 'placeholder',
        disabled: 'disabled',
        readonly: 'readonly',
        minlength: 'minlength',
        maxlength: 'maxlength',
        min: 'min',
        max: 'max',
        step: 'step',
        pattern: 'pattern',
        dropdownSearch: 'dropdown-search',
        required: 'required',
        autocapitalize: 'autocapitalize',
        autocorrect: 'autocorrect',
        autocomplete: 'autocomplete',
        autofocus: 'autofocus',
        spellcheck: 'spellcheck',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        clearable: 'clearable',
        togglePassword: 'toggle-password',
        inputmode: 'inputmode',
        line: 'line'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixItemPickerEvents = {
    onSixItemPickerChange: EventName<SixItemPickerCustomEvent<SixItemPickerChangePayload>>,
    onSixItemPickerChangeDebounced: EventName<SixItemPickerCustomEvent<SixItemPickerChangePayload>>
};

export const SixItemPicker: StencilReactComponent<SixItemPickerElement, SixItemPickerEvents> = /*@__PURE__*/ createComponent<SixItemPickerElement, SixItemPickerEvents>({
    tagName: 'six-item-picker',
    properties: {
        value: 'value',
        type: 'type',
        min: 'min',
        max: 'max',
        roundtrip: 'roundtrip',
        step: 'step',
        items: 'items',
        padded: 'padded',
        paddingLength: 'padding-length',
        paddingChar: 'padding-char',
        paddingDirection: 'padding-direction',
        timeout: 'timeout',
        interval: 'interval',
        debounce: 'debounce'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixLanguageSwitcherEvents = { onSixLanguageSwitcherChange: EventName<SixLanguageSwitcherCustomEvent<SixLanguageSwitcherChangePayload>> };

export const SixLanguageSwitcher: StencilReactComponent<SixLanguageSwitcherElement, SixLanguageSwitcherEvents> = /*@__PURE__*/ createComponent<SixLanguageSwitcherElement, SixLanguageSwitcherEvents>({
    tagName: 'six-language-switcher',
    properties: {
        selected: 'selected',
        languages: 'languages'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixLayoutGridEvents = NonNullable<unknown>;

export const SixLayoutGrid: StencilReactComponent<SixLayoutGridElement, SixLayoutGridEvents> = /*@__PURE__*/ createComponent<SixLayoutGridElement, SixLayoutGridEvents>({
    tagName: 'six-layout-grid',
    properties: { columns: 'columns' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixLogoEvents = NonNullable<unknown>;

export const SixLogo: StencilReactComponent<SixLogoElement, SixLogoEvents> = /*@__PURE__*/ createComponent<SixLogoElement, SixLogoEvents>({
    tagName: 'six-logo',
    properties: { brand: 'brand' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixMainContainerEvents = NonNullable<unknown>;

export const SixMainContainer: StencilReactComponent<SixMainContainerElement, SixMainContainerEvents> = /*@__PURE__*/ createComponent<SixMainContainerElement, SixMainContainerEvents>({
    tagName: 'six-main-container',
    properties: { padded: 'padded' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixMenuEvents = { onSixMenuItemSelected: EventName<SixMenuCustomEvent<SixMenuItemSelectedPayload>> };

export const SixMenu: StencilReactComponent<SixMenuElement, SixMenuEvents> = /*@__PURE__*/ createComponent<SixMenuElement, SixMenuEvents>({
    tagName: 'six-menu',
    properties: {
        removeBoxShadow: 'remove-box-shadow',
        items: 'items',
        itemsShown: 'items-shown',
        virtualScroll: 'virtual-scroll',
        itemSize: 'item-size',
        scrollingDebounce: 'scrolling-debounce',
        disableKeyboardHandling: 'disable-keyboard-handling'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixMenuDividerEvents = NonNullable<unknown>;

export const SixMenuDivider: StencilReactComponent<SixMenuDividerElement, SixMenuDividerEvents> = /*@__PURE__*/ createComponent<SixMenuDividerElement, SixMenuDividerEvents>({
    tagName: 'six-menu-divider',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixMenuItemEvents = NonNullable<unknown>;

export const SixMenuItem: StencilReactComponent<SixMenuItemElement, SixMenuItemEvents> = /*@__PURE__*/ createComponent<SixMenuItemElement, SixMenuItemEvents>({
    tagName: 'six-menu-item',
    properties: {
        checkType: 'check-type',
        checked: 'checked',
        value: 'value',
        disabled: 'disabled'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixMenuLabelEvents = NonNullable<unknown>;

export const SixMenuLabel: StencilReactComponent<SixMenuLabelElement, SixMenuLabelEvents> = /*@__PURE__*/ createComponent<SixMenuLabelElement, SixMenuLabelEvents>({
    tagName: 'six-menu-label',
    properties: {},
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixPictoEvents = NonNullable<unknown>;

export const SixPicto: StencilReactComponent<SixPictoElement, SixPictoEvents> = /*@__PURE__*/ createComponent<SixPictoElement, SixPictoEvents>({
    tagName: 'six-picto',
    properties: { size: 'size' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixProgressBarEvents = NonNullable<unknown>;

export const SixProgressBar: StencilReactComponent<SixProgressBarElement, SixProgressBarEvents> = /*@__PURE__*/ createComponent<SixProgressBarElement, SixProgressBarEvents>({
    tagName: 'six-progress-bar',
    properties: {
        percentage: 'percentage',
        indeterminate: 'indeterminate'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixProgressRingEvents = NonNullable<unknown>;

export const SixProgressRing: StencilReactComponent<SixProgressRingElement, SixProgressRingEvents> = /*@__PURE__*/ createComponent<SixProgressRingElement, SixProgressRingEvents>({
    tagName: 'six-progress-ring',
    properties: {
        size: 'size',
        strokeWidth: 'stroke-width',
        percentage: 'percentage'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixRadioEvents = {
    onSixRadioBlur: EventName<SixRadioCustomEvent<EmptyPayload>>,
    onSixRadioChange: EventName<SixRadioCustomEvent<EmptyPayload>>,
    onSixRadioFocus: EventName<SixRadioCustomEvent<EmptyPayload>>
};

export const SixRadio: StencilReactComponent<SixRadioElement, SixRadioEvents> = /*@__PURE__*/ createComponent<SixRadioElement, SixRadioEvents>({
    tagName: 'six-radio',
    properties: {
        name: 'name',
        value: 'value',
        disabled: 'disabled',
        checked: 'checked',
        invalid: 'invalid'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixRangeEvents = {
    onSixRangeChange: EventName<SixRangeCustomEvent<EmptyPayload>>,
    onSixRangeBlur: EventName<SixRangeCustomEvent<EmptyPayload>>,
    onSixRangeFocus: EventName<SixRangeCustomEvent<EmptyPayload>>
};

export const SixRange: StencilReactComponent<SixRangeElement, SixRangeEvents> = /*@__PURE__*/ createComponent<SixRangeElement, SixRangeEvents>({
    tagName: 'six-range',
    properties: {
        name: 'name',
        value: 'value',
        required: 'required',
        helpText: 'help-text',
        disabled: 'disabled',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        min: 'min',
        max: 'max',
        step: 'step',
        tooltip: 'tooltip',
        tooltipFormatter: 'tooltip-formatter'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixRootEvents = NonNullable<unknown>;

export const SixRoot: StencilReactComponent<SixRootElement, SixRootEvents> = /*@__PURE__*/ createComponent<SixRootElement, SixRootEvents>({
    tagName: 'six-root',
    properties: {
        padded: 'padded',
        stage: 'stage',
        version: 'version'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSearchFieldEvents = { onSixSearchFieldChange: EventName<SixSearchFieldCustomEvent<SixSearchFieldChangePayload>> };

export const SixSearchField: StencilReactComponent<SixSearchFieldElement, SixSearchFieldEvents> = /*@__PURE__*/ createComponent<SixSearchFieldElement, SixSearchFieldEvents>({
    tagName: 'six-search-field',
    properties: {
        placeholder: 'placeholder',
        debounce: 'debounce',
        disabled: 'disabled',
        value: 'value',
        clearable: 'clearable'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSelectEvents = {
    onSixSelectChange: EventName<SixSelectCustomEvent<SixSelectChangePayload>>,
    onSixSelectFocus: EventName<SixSelectCustomEvent<EmptyPayload>>,
    onSixSelectBlur: EventName<SixSelectCustomEvent<EmptyPayload>>
};

export const SixSelect: StencilReactComponent<SixSelectElement, SixSelectEvents> = /*@__PURE__*/ createComponent<SixSelectElement, SixSelectEvents>({
    tagName: 'six-select',
    properties: {
        multiple: 'multiple',
        selectAllButton: 'select-all-button',
        selectAllText: 'select-all-text',
        disabled: 'disabled',
        name: 'name',
        placeholder: 'placeholder',
        filterPlaceholder: 'filter-placeholder',
        filterDebounce: 'filter-debounce',
        size: 'size',
        hoist: 'hoist',
        value: 'value',
        pill: 'pill',
        helpText: 'help-text',
        required: 'required',
        clearable: 'clearable',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        line: 'line',
        filter: 'filter',
        asyncFilter: 'async-filter',
        autocomplete: 'autocomplete',
        inputDebounce: 'input-debounce',
        options: 'options',
        virtualScroll: 'virtual-scroll'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSidebarEvents = {
    onSixSidebarShow: EventName<SixSidebarCustomEvent<EmptyPayload>>,
    onSixSidebarAfterShow: EventName<SixSidebarCustomEvent<EmptyPayload>>,
    onSixSidebarHide: EventName<SixSidebarCustomEvent<EmptyPayload>>,
    onSixSidebarAfterHide: EventName<SixSidebarCustomEvent<EmptyPayload>>,
    onSixSidebarInitialFocus: EventName<SixSidebarCustomEvent<EmptyPayload>>
};

export const SixSidebar: StencilReactComponent<SixSidebarElement, SixSidebarEvents> = /*@__PURE__*/ createComponent<SixSidebarElement, SixSidebarEvents>({
    tagName: 'six-sidebar',
    properties: {
        position: 'position',
        open: 'open',
        width: 'width',
        toggled: 'toggled'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSidebarItemEvents = NonNullable<unknown>;

export const SixSidebarItem: StencilReactComponent<SixSidebarItemElement, SixSidebarItemEvents> = /*@__PURE__*/ createComponent<SixSidebarItemElement, SixSidebarItemEvents>({
    tagName: 'six-sidebar-item',
    properties: {
        value: 'value',
        selected: 'selected',
        disabled: 'disabled',
        icon: 'icon',
        href: 'href'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSidebarItemGroupEvents = NonNullable<unknown>;

export const SixSidebarItemGroup: StencilReactComponent<SixSidebarItemGroupElement, SixSidebarItemGroupEvents> = /*@__PURE__*/ createComponent<SixSidebarItemGroupElement, SixSidebarItemGroupEvents>({
    tagName: 'six-sidebar-item-group',
    properties: {
        name: 'name',
        icon: 'icon',
        value: 'value',
        open: 'open',
        summaryIcon: 'summary-icon',
        href: 'href'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSpinnerEvents = NonNullable<unknown>;

export const SixSpinner: StencilReactComponent<SixSpinnerElement, SixSpinnerEvents> = /*@__PURE__*/ createComponent<SixSpinnerElement, SixSpinnerEvents>({
    tagName: 'six-spinner',
    properties: {
        logo: 'logo',
        six: 'six'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixStageIndicatorEvents = NonNullable<unknown>;

export const SixStageIndicator: StencilReactComponent<SixStageIndicatorElement, SixStageIndicatorEvents> = /*@__PURE__*/ createComponent<SixStageIndicatorElement, SixStageIndicatorEvents>({
    tagName: 'six-stage-indicator',
    properties: { stage: 'stage' },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixSwitchEvents = {
    onSixSwitchBlur: EventName<CustomEvent<boolean>>,
    onSixSwitchChange: EventName<CustomEvent<boolean>>,
    onSixSwitchFocus: EventName<SixSwitchCustomEvent<EmptyPayload>>
};

export const SixSwitch: StencilReactComponent<SixSwitchElement, SixSwitchEvents> = /*@__PURE__*/ createComponent<SixSwitchElement, SixSwitchEvents>({
    tagName: 'six-switch',
    properties: {
        name: 'name',
        value: 'value',
        disabled: 'disabled',
        required: 'required',
        checked: 'checked',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTabEvents = { onSixTabClose: EventName<SixTabCustomEvent<EmptyPayload>> };

export const SixTab: StencilReactComponent<SixTabElement, SixTabEvents> = /*@__PURE__*/ createComponent<SixTabElement, SixTabEvents>({
    tagName: 'six-tab',
    properties: {
        panel: 'panel',
        active: 'active',
        closable: 'closable',
        disabled: 'disabled'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTabGroupEvents = {
    onSixTabShow: EventName<SixTabGroupCustomEvent<SixTabShowPayload>>,
    onSixTabHide: EventName<SixTabGroupCustomEvent<SixTabHidePayload>>
};

export const SixTabGroup: StencilReactComponent<SixTabGroupElement, SixTabGroupEvents> = /*@__PURE__*/ createComponent<SixTabGroupElement, SixTabGroupEvents>({
    tagName: 'six-tab-group',
    properties: {
        placement: 'placement',
        noScrollControls: 'no-scroll-controls'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTabPanelEvents = NonNullable<unknown>;

export const SixTabPanel: StencilReactComponent<SixTabPanelElement, SixTabPanelEvents> = /*@__PURE__*/ createComponent<SixTabPanelElement, SixTabPanelEvents>({
    tagName: 'six-tab-panel',
    properties: {
        name: 'name',
        active: 'active'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTagEvents = { onSixTagClear: EventName<SixTagCustomEvent<EmptyPayload>> };

export const SixTag: StencilReactComponent<SixTagElement, SixTagEvents> = /*@__PURE__*/ createComponent<SixTagElement, SixTagEvents>({
    tagName: 'six-tag',
    properties: {
        type: 'type',
        size: 'size',
        pill: 'pill',
        clearable: 'clearable'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTextareaEvents = {
    onSixTextareaChange: EventName<SixTextareaCustomEvent<EmptyPayload>>,
    onSixTextareaInput: EventName<SixTextareaCustomEvent<EmptyPayload>>,
    onSixTextareaFocus: EventName<SixTextareaCustomEvent<EmptyPayload>>,
    onSixTextareaBlur: EventName<SixTextareaCustomEvent<EmptyPayload>>
};

export const SixTextarea: StencilReactComponent<SixTextareaElement, SixTextareaEvents> = /*@__PURE__*/ createComponent<SixTextareaElement, SixTextareaEvents>({
    tagName: 'six-textarea',
    properties: {
        size: 'size',
        name: 'name',
        value: 'value',
        helpText: 'help-text',
        placeholder: 'placeholder',
        rows: 'rows',
        resize: 'resize',
        disabled: 'disabled',
        readonly: 'readonly',
        minlength: 'minlength',
        maxlength: 'maxlength',
        required: 'required',
        label: 'label',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        invalid: 'invalid',
        autocapitalize: 'autocapitalize',
        autocorrect: 'autocorrect',
        autocomplete: 'autocomplete',
        autofocus: 'autofocus',
        spellcheck: 'spellcheck',
        inputmode: 'inputmode'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTileEvents = {
    onSixTileClosed: EventName<SixTileCustomEvent<EmptyPayload>>,
    onSixTileSelected: EventName<SixTileCustomEvent<EmptyPayload>>
};

export const SixTile: StencilReactComponent<SixTileElement, SixTileEvents> = /*@__PURE__*/ createComponent<SixTileElement, SixTileEvents>({
    tagName: 'six-tile',
    properties: {
        label: 'label',
        iconName: 'icon-name',
        closeable: 'closeable',
        elevated: 'elevated',
        disableTooltip: 'disable-tooltip',
        disabled: 'disabled',
        size: 'size'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTimepickerEvents = {
    onSixTimepickerChange: EventName<SixTimepickerCustomEvent<SixTimepickerChange>>,
    onSixTimepickerChangeDebounced: EventName<SixTimepickerCustomEvent<SixTimepickerChange>>,
    onSixTimepickerClear: EventName<SixTimepickerCustomEvent<EmptyPayload>>
};

export const SixTimepicker: StencilReactComponent<SixTimepickerElement, SixTimepickerEvents> = /*@__PURE__*/ createComponent<SixTimepickerElement, SixTimepickerEvents>({
    tagName: 'six-timepicker',
    properties: {
        format: 'format',
        separator: 'separator',
        value: 'value',
        open: 'open',
        inline: 'inline',
        readonly: 'readonly',
        disabled: 'disabled',
        placement: 'placement',
        size: 'size',
        required: 'required',
        placeholder: 'placeholder',
        errorText: 'error-text',
        errorTextCount: 'error-text-count',
        label: 'label',
        invalid: 'invalid',
        name: 'name',
        clearable: 'clearable',
        iconPosition: 'icon-position',
        hoist: 'hoist',
        timeout: 'timeout',
        interval: 'interval',
        defaultTime: 'default-time',
        debounce: 'debounce'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});

export type SixTooltipEvents = {
    onSixTooltipShow: EventName<SixTooltipCustomEvent<EmptyPayload>>,
    onSixTooltipAfterShow: EventName<SixTooltipCustomEvent<EmptyPayload>>,
    onSixTooltipHide: EventName<SixTooltipCustomEvent<EmptyPayload>>,
    onSixTooltipAfterHide: EventName<SixTooltipCustomEvent<EmptyPayload>>
};

export const SixTooltip: StencilReactComponent<SixTooltipElement, SixTooltipEvents> = /*@__PURE__*/ createComponent<SixTooltipElement, SixTooltipEvents>({
    tagName: 'six-tooltip',
    properties: {
        content: 'content',
        placement: 'placement',
        disabled: 'disabled',
        distance: 'distance',
        open: 'open',
        skidding: 'skidding',
        trigger: 'trigger'
    },
    hydrateModule: import('@six-group/ui-library/hydrate'),
    serializeShadowRoot
});
