name: Display Variables

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release. Format vx.x.x(-[rc|beta].x)'
        required: true
        type: string

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Display variables'
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "rev-parse:  $(git rev-parse --abbrev-ref HEAD)"
